FROM python:3.8

# set a directory for the app
WORKDIR /app

# install requirements
RUN pip install -r requiremts.txt

# run trainer
RUN python ./train.py

# copy all the files to the container
COPY . .

# ENTRYPOINT []

EXPOSE 5000

CMD ["mlflow ui"]